url = https://tutorialsninja.com/demo/
browserName = chrome   
validEmail = manyachippa@gmail.com
validPassword = 12345 
//these are used in all the testfiles so created a properties file and this is called hardcoding the details in a file. 